version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
     - checkout
        
     - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
            gradle jar
     - store_artifacts:
        path: /tmp/artifact-1
            